# Generated by Django 5.1.5 on 2025-03-11 04:39

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_memory_user_alter_podcast_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Occasion', models.CharField(choices=[('WOMEN_DAY', 'روز زن'), ('MOTHERS_DAY', 'روز مادر'), ('STUDENT_DAY', 'روز دانش اموز'), ('LABOR_DAY', 'روز کارگر'), ('CUSTOM', 'سفارشی')], default='WOMEN_DAY', max_length=255)),
                ('Recipients_name_surname', models.CharField(max_length=300)),
                ('caption', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('time', models.CharField(choices=[('2min', '2دقیقه'), ('5min', '5دقیقه'), ('10min', '10دقیقه'), ('15min', '15دقیقه')], default='2min', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/memory/delcast/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.AlterField(
            model_name='memory',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/memory/voice_memory/'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/memory/Memory_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(upload_to='templates/memory/podcast_image/'),
        ),
        migrations.CreateModel(
            name='PodcastDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='memory.podcast')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
