# Generated by Django 5.1.5 on 2025-03-11 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_delcast_alter_memory_audio_file_alter_memory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/memory/voice_podcast', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
