# Generated by Django 5.1.7 on 2025-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_delcast_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='delcast',
            name='Gender',
            field=models.CharField(choices=[('male', 'مذکر'), ('female', 'مونث')], default='male', max_length=255),
        ),
        migrations.AddField(
            model_name='delcast',
            name='favorites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delcast',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
