# Generated by Django 5.1.5 on 2025-03-07 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'ریال'), ('DOLLAR', 'دلار'), ('EURO', 'یورو'), ('POUND', 'پوند'), ('IQD', 'دینار عراق'), ('LIRA', 'لیر ترکیه')], default='IRR', max_length=9)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کمک مالی',
                'verbose_name_plural': 'کمک\u200cهای مالی',
                'ordering': ('-date',),
            },
        ),
    ]
