# Generated by Django 5.1.5 on 2025-03-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_donate',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
