# Generated by Django 5.1.5 on 2025-03-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_total_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='39672.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
